services:
  backend:
    build:
      context: ../RentokilSelfServiceBackendUni
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../RentokilSelfServiceBackendUni/.env
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - JWT_SECRET_KEY=RentokilLocalSecretKey2026_Secure
    volumes:
      - backend_data:/home/user/rentokilselfservice/Service/data

  frontend:
    build:
      context: ../RentokilSelfServiceFrontendUni
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ../RentokilSelfServiceFrontendUni/.env
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  backend_data:
